[planets]
names = ["Sun", "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]
positional_constant = 200.0

[camera]
speed = 15000.0
yaw = -26.55
pitch = -20.79
position = [552.35, 37.05, 50.06]

[Sun]
mass = 1.989e30
radius = 696340e3
distance = 0
orbit_velocity = 0.0
model = "sphere.obj"
texture = "Sun.png"

[Mercury]
mass = 3.285e23
radius = 2439.7e3
distance = 58e9
orbit_velocity = 47.36e3
model = "Mercury.obj"
texture = "Mercury.png"

[Venus]
mass = 4.867e24
radius = 6051.8e3
distance = 107.58e9
orbit_velocity = 35.02e3
model = "Venus.obj"
texture = "Venus.png"

[Earth]
mass = 5.972e24
radius = 6371e3
distance = 150.88e9
orbit_velocity = 29.78e3
model = "earth.obj"
texture = "earth.jpg"

[Mars]
mass = 6.39e23
radius = 3389.5e3
distance = 267.73e9
orbit_velocity = 24.08e3
model = "Mars.obj"
texture = "Mars.png"

[Jupiter]
mass = 1.898e27
radius = 69911e3
distance = 741.1e9
orbit_velocity = 13.06e3
model = "sphere.obj"
texture = "Jupiter.png"

[Saturn]
mass = 5.683e26
radius = 58232e3
distance = 1.4648e12
orbit_velocity = 9.67e3
model = "sphere.obj"
texture = "Saturn.png"

[Uranus]
mass = 8.681e25
radius = 25362e3
distance = 2.9387e12
orbit_velocity = 6.79e3
model = "sphere.obj"
texture = "Uranus.png"

[Neptune]
mass = 1.024e26
radius = 24622e3
distance = 4.4732e12
orbit_velocity = 5.45e3
model = "sphere.obj"
texture = "Neptune.png"

[Pluto]
mass = 1.30900e22
radius = 1188.3e3
distance = 5.9e12
orbit_velocity = 4.64e3
model = "sphere.obj"
texture = "Pluto.png"